include:
  - ./proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: mysql
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test
      DB_TABLE: requests_new
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.20.0.5
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      backend:
